<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Error  File Size is large From 5MB</name>
   <tag></tag>
   <elementGuidId>12a1c903-d826-43d9-8545-1115cda8fba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c36-2.ng-star-inserted.ng-trigger.ng-trigger-flyInOut.ngx-toastr.toast-error.ng-animating</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9da19859-143a-4383-a96b-44cf858eb98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c36-2 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-error ng-animating</value>
      <webElementGuid>ad0f07bd-55b8-4ce7-8441-a25b2b6f61dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Error  File Size is large From 5MB </value>
      <webElementGuid>8cde6818-9d83-47e1-8832-308f460feddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;ng-tns-c36-2 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-error ng-animating&quot;]</value>
      <webElementGuid>667c0fc1-0793-469f-acf0-5935c99dc25d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>1f09bd5c-3f57-4030-a498-f6e4619c1266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[4]</value>
      <webElementGuid>d085d32c-2010-4ad3-8179-2c76b0c13aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[4]</value>
      <webElementGuid>a85d86e9-1b9a-42ae-8991-b5d1c674bb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>fa21191a-e4c6-4aaf-a01d-b2af79c7df23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Error  File Size is large From 5MB ' or . = ' Error  File Size is large From 5MB ')]</value>
      <webElementGuid>64b54430-825f-4576-aacc-3f2267df7353</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
