<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Success  Resume already uploaded</name>
   <tag></tag>
   <elementGuidId>8d6793c0-9f61-441d-9ff1-95d0b77a562c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c36-14.ng-star-inserted.ng-trigger.ng-trigger-flyInOut.ngx-toastr.toast-success.ng-animating</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53bb5040-f8b7-4e32-8c55-715bc84149bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c36-14 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-success ng-animating</value>
      <webElementGuid>023bb014-7376-4202-969f-dba1dd89e818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Success  Resume already uploaded. </value>
      <webElementGuid>e86bc6c3-1ef6-4ecd-a7ea-14f6b4ee62ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;ng-tns-c36-14 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-success ng-animating&quot;]</value>
      <webElementGuid>b6c883b6-c126-4e28-82ec-f52c618b6f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>a58a1bf1-32ff-4433-afc0-d608d11909d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[4]</value>
      <webElementGuid>bb612c4d-5111-42a8-b8e1-70b14a9bf981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[4]</value>
      <webElementGuid>397fc28b-a8ee-4030-b62f-9c25d79ac59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>0a033cb8-c337-4f96-b0a4-2407739e9db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Success  Resume already uploaded. ' or . = ' Success  Resume already uploaded. ')]</value>
      <webElementGuid>8574d96c-1029-4eae-a50b-8a4735f36994</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
