<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Uploaded Resume_image</name>
   <tag></tag>
   <elementGuidId>82c07f87-57d9-4896-911a-172ea0ff4e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41734c4e-add5-451a-a9c1-6773b4aad8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>ad3e9c1c-4c66-41ca-b4f4-c94c07ac3c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>c2f6ff73-78ae-4ecf-b724-26583121aa10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>32c9e663-05e2-4a8a-bf8d-73c75afa8cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf</value>
      <webElementGuid>aee2339f-03a4-48a1-9182-42f4f55abdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choose-file-input</value>
      <webElementGuid>bc8db720-a4af-48b1-9b7d-35aa778145f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image&quot;)</value>
      <webElementGuid>a5f2f2cc-17b2-4be1-aa9c-87c78584107d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='image']</value>
      <webElementGuid>33b1d3bb-9df3-448e-9af8-295da979ea89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uploaded']/div/div/div/div/input</value>
      <webElementGuid>4e0ef858-b023-40fc-9930-0232a7dfa57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>90cb6812-ebf2-4e36-8e99-35ff68d61855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'image' and @name = 'image']</value>
      <webElementGuid>6ce46354-c54c-40a0-9f7f-5f580cdd81cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
