<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_last</name>
   <tag></tag>
   <elementGuidId>ca23220c-9239-4b6a-90b0-344865828539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#last</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='last']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80b6212d-ece5-4e83-85af-9ae5323d24d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>324c0265-53f2-498d-8837-a348f4950bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>39544e80-4016-4838-9289-b4a7fdae4ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>last</value>
      <webElementGuid>c7f4ecac-1f08-4a10-b7d9-82e5adee68ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>regular-font-size form-control rounded-0 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6356e489-2e44-4bce-a60f-76fd6baca1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;last&quot;)</value>
      <webElementGuid>f7a98b15-ae50-4abd-8ce8-8cc9f9cb6dee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='last']</value>
      <webElementGuid>55db71ad-8139-45d2-98b4-30325a8d0b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>eebbcd89-045e-49ac-ba2a-fdade3355604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'last']</value>
      <webElementGuid>45998881-9135-4d96-a9bd-37e90ef9b0bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
