<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postcode_poscode</name>
   <tag></tag>
   <elementGuidId>dddee988-a5cd-4f28-9c39-1388a589a29c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#poscode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='poscode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5493cfa0-965a-40c0-907a-5f37d9d25c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fc560770-9ca4-4899-b0e4-ffc92876a120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>postcode</value>
      <webElementGuid>a37e5cea-372c-4a6b-b206-3211a53d2e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>poscode</value>
      <webElementGuid>8d7b6181-c051-4e41-9ed1-0cf03f43cd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>regular-font-size form-control rounded-0 ng-pristine ng-valid ng-touched</value>
      <webElementGuid>168565a3-7580-4760-a687-8bc617ff38c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;poscode&quot;)</value>
      <webElementGuid>157110f2-0680-45f7-9e10-99d979eeaa65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='poscode']</value>
      <webElementGuid>db92b40c-6605-4fe9-8152-c39071518034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/div/input</value>
      <webElementGuid>e4ae489b-c2ea-4425-b1ca-4774ac0b02dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'poscode']</value>
      <webElementGuid>448cc7eb-9760-4919-93eb-e1a4297f67c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
