<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_status_giveAccessResume</name>
   <tag></tag>
   <elementGuidId>fe3f4bdf-9651-4934-ac1c-e63242bfba0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8863de7e-63e5-42da-82cd-da34fb3f4404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a0cff57a-aaa6-4825-8d21-d58be4eb4048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>request_for_resume</value>
      <webElementGuid>343fda9b-5b8c-4d30-a785-772b660bfe65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-check-input ng-valid ng-dirty ng-touched</value>
      <webElementGuid>45a05a51-e535-4d10-b507-37ec063ec16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-candidate-edit-profile[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;profile-set-up job-seeker-page py-lg-5 py-4&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;row gx-xl-5&quot;]/div[@class=&quot;col-md-3 mb-3 align-self-end&quot;]/div[1]/div[@class=&quot;d-inline-block position-relative checkbox-form-group&quot;]/input[@class=&quot;custom-check-input ng-valid ng-dirty ng-touched&quot;]</value>
      <webElementGuid>1a248262-456b-40af-bda5-ab61428a7bcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>749797a0-daa5-468a-941c-da1c17f2ab73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>2e3214c5-93fb-468f-a1a0-a3e5cd507a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>49cb9fdc-9e86-49f2-9e02-484831898d8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
