<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_status_activeLooking</name>
   <tag></tag>
   <elementGuidId>a8cd7ba5-c7a1-4575-ab02-071520bb7e1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.custom-check-input.ng-valid.ng-dirty.ng-touched</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41d60339-af30-47a2-9092-9e31483384db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7476ab93-9435-42d1-8837-d019b90b0582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>actively_looking</value>
      <webElementGuid>5ea99704-2319-4207-be98-2b47f2ac1d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-check-input ng-valid ng-dirty ng-touched</value>
      <webElementGuid>c86425f4-292d-4a0b-90e4-bf1dbaaf70d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-candidate-edit-profile[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;profile-set-up job-seeker-page py-lg-5 py-4&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;row gx-xl-5&quot;]/div[@class=&quot;col-md-3 mb-3 align-self-end&quot;]/div[1]/div[@class=&quot;d-inline-block position-relative checkbox-form-group&quot;]/input[@class=&quot;custom-check-input ng-valid ng-dirty ng-touched&quot;]</value>
      <webElementGuid>2ee4c89a-e262-425a-91c4-cd639be778bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>68e3a7ad-141a-4ba4-924c-6cb96d6362a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>0d698d8b-9b3e-45d4-8494-31eedacd669f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>c64eff95-90a3-438f-aeb8-2f912d018e32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
