<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_interestedCrowdtesting</name>
   <tag></tag>
   <elementGuidId>aa4c3455-60e9-474c-a0cc-df989f58bd5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#again</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='again']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e6355ed-a52c-4679-ad8f-404d9aa2f706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d18fefef-9c09-48fc-b473-259110bcfd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>crowdtesting</value>
      <webElementGuid>8d9c3696-e4b3-46fb-919c-3f8d383b70d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>again</value>
      <webElementGuid>494f8d7b-0ea3-4a3c-8279-2946c7eac948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-check-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>20d491df-7ad9-424f-a274-de4e401348b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;again&quot;)</value>
      <webElementGuid>1be71829-68a7-43d4-81bb-02a2dfa34241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='again']</value>
      <webElementGuid>022a46a6-bc94-45af-a987-d50a68b058eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/input</value>
      <webElementGuid>448480b3-95eb-4457-a6c4-9a6f9094d803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'again']</value>
      <webElementGuid>e130a026-8a3d-4f81-85a9-032cc861fe6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
