<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_first</name>
   <tag></tag>
   <elementGuidId>cdd958d0-2ddc-4ebf-967d-5e8a03fa08a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='first']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b38f369-bb30-48f8-bbf8-97521cc593a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>036580de-9c0e-4f06-b4af-55e913d5d015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>first_name</value>
      <webElementGuid>17d2191c-fe0d-4816-ac31-7f65f1c90780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>first</value>
      <webElementGuid>a7f223f5-9fd3-47f6-827b-ece210f37bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>regular-font-size form-control rounded-0 ng-pristine ng-valid ng-touched</value>
      <webElementGuid>6c37617a-4734-4fa4-962f-6e6358ff361a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;first&quot;)</value>
      <webElementGuid>2431c6ef-1d69-4c9e-9d96-89beb25a3962</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='first']</value>
      <webElementGuid>1e2f208c-297a-4d69-92ee-bddd1bc42eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>9ac531ce-9c0e-482d-9d8e-7b842ff5f19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'first']</value>
      <webElementGuid>94930d3f-213a-42b3-a970-e4d46ccd1893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
