<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keyword Search_keyword_search</name>
   <tag></tag>
   <elementGuidId>880ed564-3553-4634-b513-eff1a935ec7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keyword_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keyword_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55551cc3-cf09-4f74-9b69-57f0d54ad3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74dabb41-8a1e-4459-b87e-754ebbd32588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>keywords</value>
      <webElementGuid>b5fb4923-6be3-4e5f-8d2f-cdc31c478e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyword_search</value>
      <webElementGuid>762ea1b4-71ec-44d0-b683-318de9df5613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>regular-font-size form-control rounded-0 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9a8d52c9-0560-49ce-947c-1d924591aa67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyword_search&quot;)</value>
      <webElementGuid>2070e824-542e-4dcf-8638-289d6d579ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keyword_search']</value>
      <webElementGuid>9fa1c9c1-72b5-42d2-82ed-046134cfc256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/input</value>
      <webElementGuid>ec138c18-a2f1-41db-824d-b3c8b7252300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'keyword_search']</value>
      <webElementGuid>5035a08e-93ed-4e65-9749-c8a34c8b77a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
