<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_WFH</name>
   <tag></tag>
   <elementGuidId>81dda4b8-9fcf-4fd6-b76c-df248be55597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;work2&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>070f6990-9d39-44c6-87a2-58190f07ee7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>work1</value>
      <webElementGuid>cd8d6390-7ee3-45c1-b797-c4f0f183fe8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label custom-check-label</value>
      <webElementGuid>121360e8-c5cd-4845-b745-065ab822e606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WFH</value>
      <webElementGuid>0bb6bd6d-34b6-4dea-8277-84f242c79ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-candidate-edit-profile[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;profile-set-up job-seeker-page py-lg-5 py-4&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;row gx-xl-5&quot;]/div[@class=&quot;col-lg-6 mb-3&quot;]/div[1]/div[@class=&quot;row gx-sm-4 gx-1 form-radio-btns&quot;]/div[@class=&quot;col-4&quot;]/div[@class=&quot;form-check custom-form-check position-relative&quot;]/label[@class=&quot;form-check-label custom-check-label&quot;]</value>
      <webElementGuid>818f6333-7b98-4018-a2e9-5d538722e769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Site Office'])[1]/following::label[1]</value>
      <webElementGuid>ba784579-58fb-45ed-a41f-e3447e2911a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ii)'])[1]/following::label[2]</value>
      <webElementGuid>532dd1f6-247b-4158-93d0-ce6823a14bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Both'])[1]/preceding::label[1]</value>
      <webElementGuid>40b9af1d-c857-45ed-9f3f-6ab87d9f59b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brief Introduction About Self'])[1]/preceding::label[2]</value>
      <webElementGuid>ba8b3d6d-73d1-4c30-85a8-cb24237885e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WFH']/parent::*</value>
      <webElementGuid>8b4a8fab-e21a-408e-9f58-f63fbdba23dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div/div[2]/div/label</value>
      <webElementGuid>8a61c822-09db-4821-9b16-058b750ed6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'WFH' or . = 'WFH')]</value>
      <webElementGuid>5eff5625-1c15-45ad-ab77-af3ea30d0c6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
