<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Brief Introduction About Self_introduction</name>
   <tag></tag>
   <elementGuidId>0072ce53-08e6-4a92-80a9-a8bf8091603e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#introduction</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='introduction']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>216487e3-6745-4655-a067-d8dcab94c1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>introduction</value>
      <webElementGuid>4cb75031-aa26-4f45-81b9-9276cc28c4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>introduction</value>
      <webElementGuid>8cd9135f-401f-4723-8d43-070bc9382dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>bf9dc863-0aab-46e9-b433-17f339c222e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>regular-font-size form-control rounded-0 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7d01b68d-161e-4d4e-9668-45ae9cf85153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;introduction&quot;)</value>
      <webElementGuid>8d9a22e6-4682-41e8-92c3-69f5de3b2a06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='introduction']</value>
      <webElementGuid>4c5c5267-92e3-49b0-b4a7-35d48d849ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1b8ff51f-49c9-4b59-9934-eb7a088f783b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'introduction']</value>
      <webElementGuid>7869caea-ad9d-405b-a88d-27e5d4fc531a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
