<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Candidate</name>
   <tag></tag>
   <elementGuidId>28874e9b-1184-41b0-9f82-f75423c0dc86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.register-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Candidate')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d9ec270-242d-4c24-ac1b-2a73aba3cf28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>routerlink</name>
      <type>Main</type>
      <value>/candidate-registration</value>
      <webElementGuid>59f92bfe-8b11-474c-ad94-4ba9208f8f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-btn</value>
      <webElementGuid>3da256b3-1f1d-4765-9f03-14f57680e1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/candidate-registration</value>
      <webElementGuid>b50a651f-d7fc-4b4a-9ec7-3dadd0086bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Candidate</value>
      <webElementGuid>8562d325-87c8-4693-a42e-1654f68e4672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-header[1]/header[@class=&quot;header header-responsive employe-header&quot;]/div[@class=&quot;register-btn-part ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;register-btn&quot;]</value>
      <webElementGuid>2cc13a13-95e9-48cf-b64e-c4bc6bac993b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Candidate')]</value>
      <webElementGuid>9a22b37c-d967-4f85-acd9-d5a800f7c907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Jobs'])[1]/following::a[1]</value>
      <webElementGuid>4f548737-0a24-486f-ac30-d7c47ccd10ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>72965545-2b47-468b-a177-62b2fdbf1820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start hiring'])[1]/preceding::a[2]</value>
      <webElementGuid>fbf519c0-01e5-41b7-81f8-fe3c53a0810b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='candidates!'])[1]/preceding::a[2]</value>
      <webElementGuid>6ac32fdd-28e9-4d12-9202-167873655daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Candidate']/parent::*</value>
      <webElementGuid>93515f34-6dbb-4dd3-8200-e3a735b095a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/candidate-registration')]</value>
      <webElementGuid>da11962d-1588-4149-aab7-1e295667e441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>25cebfd1-8c41-4774-a979-2e77343659a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/candidate-registration' and (text() = 'Candidate' or . = 'Candidate')]</value>
      <webElementGuid>a3aa492c-f93d-46ab-bc68-e3aee37eabde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
