<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign Up_promotion</name>
   <tag></tag>
   <elementGuidId>5b2c8e50-8a41-49d0-863f-f9b60478b9b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#promotion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='promotion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1437a046-95d4-4542-a74e-71374019fc02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9a143e68-f0d8-4cd6-8953-80f7ff4b4fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>promotion</value>
      <webElementGuid>647e6407-a2b4-4152-961a-8e790b36ca0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>promotion</value>
      <webElementGuid>81a17c42-5d47-4b29-ba58-17e84bdf75dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promotion</value>
      <webElementGuid>9ab1d6e2-1f56-49a8-9497-14c6f613fe59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-check-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>24a463b6-d5c5-46ef-8f90-cb4a3d96206d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;promotion&quot;)</value>
      <webElementGuid>7c0e977c-878b-406c-9f04-c3abb4d6af16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='promotion']</value>
      <webElementGuid>e934f2e8-5784-4d1a-bc85-09621370346d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>046304f2-f733-4a85-878d-c9bfa85b2360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'promotion' and @id = 'promotion']</value>
      <webElementGuid>9288dc1f-633f-4b37-93e3-218e26705a51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
