<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact person name_contact_person_name</name>
   <tag></tag>
   <elementGuidId>38bd1aff-4497-40fa-99cb-e984e0f6b337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contact_person_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contact_person_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c69bf76-254a-45ee-aa2e-109bad77aa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f807064-613c-4237-be77-7aef0b911eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contact_person_name</value>
      <webElementGuid>212b11ef-d56f-4117-9150-d27c9ee82976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contact_person_name</value>
      <webElementGuid>4f0ff735-f0bb-4413-a518-40e5fbc5463c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return !(event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57)</value>
      <webElementGuid>676bf57f-79ca-464d-a9d3-715634562fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-custom ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f29cd545-471d-4398-9dde-09e91092934d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact_person_name&quot;)</value>
      <webElementGuid>feadafb4-8223-4bb8-8994-2a51b3059689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contact_person_name']</value>
      <webElementGuid>8423310b-7a0b-4c24-a0ac-6abcf6e77d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f92674be-4959-4057-b2d0-0eb475ec682d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'contact_person_name']</value>
      <webElementGuid>1c46fc71-4426-4938-94ea-c81fde689c5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
