<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Registered business name_registered_b_2c5359</name>
   <tag></tag>
   <elementGuidId>ff5eb632-c002-4ec2-a1ff-65f94488aae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registered_business_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registered_business_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d77c232-e4fd-42fb-aec1-04b4e3a35cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0f2696f-48ee-4cc6-b9de-51030dbc359f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>registered_business_name</value>
      <webElementGuid>51f1db36-e289-4e48-a3d4-05b8e85fca96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registered_business_name</value>
      <webElementGuid>b70ebf3e-6630-4e25-85c8-1b32e3bbeafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registered_business_name</value>
      <webElementGuid>d639f1d4-e9d3-4500-b9f4-8c41f633c486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Same as business registration documents</value>
      <webElementGuid>c96d82db-7ed5-402e-b8c5-b5a8c8efda2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-custom ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e8cb20a2-85df-4040-964c-1e8a78d64bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registered_business_name&quot;)</value>
      <webElementGuid>b07c030f-cd91-48d8-ad36-9e41f9b90817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registered_business_name']</value>
      <webElementGuid>4ccc6c8a-39ef-4503-a057-fdf956705d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>788d75dd-0c61-4bf9-baba-0d30ce401e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'registered_business_name' and @name = 'registered_business_name' and @placeholder = 'Same as business registration documents']</value>
      <webElementGuid>096f8610-23d6-479a-bfe9-0a191a433cbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
