<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_A</name>
   <tag></tag>
   <elementGuidId>c7a8d7cd-37b5-45ee-8020-bbef1d1e708b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.alphabet-link.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'A')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11c0a9ed-879b-4b89-8c89-1c462898b43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alphabet-link active</value>
      <webElementGuid>27415766-5957-42fa-a41e-c99accb5d224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A</value>
      <webElementGuid>bce17234-4d8c-4cc1-9348-cba4e2252718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-home[@class=&quot;ng-star-inserted&quot;]/main[@class=&quot;main-page position-relative&quot;]/section[@class=&quot;alphabet-section&quot;]/div[@class=&quot;container-content&quot;]/ul[@class=&quot;alphabet-list&quot;]/li[@class=&quot;alphabet-item ng-star-inserted&quot;]/a[@class=&quot;alphabet-link active&quot;]</value>
      <webElementGuid>9fef4aa1-d40b-4224-b6fc-f6de9f87de8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'A')])[3]</value>
      <webElementGuid>af22b7cd-a517-4396-8fd1-63248f3b65d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[1]</value>
      <webElementGuid>b7bbb0ba-09e0-4db1-93cd-a9ced5379bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For You'])[1]/following::a[1]</value>
      <webElementGuid>1862e9dd-cd3d-4bb6-80ef-e0cdd67a80f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B'])[1]/preceding::a[1]</value>
      <webElementGuid>40a310e4-8ef8-4f9e-bac3-a516839088e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/preceding::a[2]</value>
      <webElementGuid>55401775-7505-4540-85d6-d8e557dc0b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A']/parent::*</value>
      <webElementGuid>0f0147c5-8d96-43e7-bc53-739f083d88d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/ul/li/a</value>
      <webElementGuid>e3a80345-05bf-469e-aca1-c5d0dbc1ec90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'A' or . = 'A')]</value>
      <webElementGuid>f62bb6cc-93ab-40a6-afab-9b6ebe3b8b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
