<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Job Application Status</name>
   <tag></tag>
   <elementGuidId>b880643c-cd6e-4ab6-96f8-c63054b99426</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>section.breadcrumb-section</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::section[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>58e36c75-1447-4522-8c5f-faac00da7c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>breadcrumb-section</value>
      <webElementGuid>f300f791-d5e1-455d-8e00-3315fcbf9085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job Application Status</value>
      <webElementGuid>d58a1ffb-6fd1-4256-a61b-8db841a99147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-application-status[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;breadcrumb-section&quot;]</value>
      <webElementGuid>3809b385-1506-4d39-88bb-1f96353015cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[2]/following::section[1]</value>
      <webElementGuid>362713d2-9e22-4429-9e8b-293ccafe9c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::section[1]</value>
      <webElementGuid>436ed651-3f55-4634-9948-eceb058a10f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter by'])[1]/preceding::section[1]</value>
      <webElementGuid>f08151fb-c057-4405-92d9-7793af2d07cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section</value>
      <webElementGuid>eada0664-5a65-4455-86bd-8baec94e48a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Job Application Status' or . = 'Job Application Status')]</value>
      <webElementGuid>f79ccb39-b9b8-4a8a-9bea-4a65ad0e2f19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
